# Generated by Django 5.2.9 on 2025-12-26 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0002_alter_voiceenrollmentjob_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceenrollmentjob',
            name='current_step',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voiceenrollmentjob',
            name='job_type',
            field=models.CharField(choices=[('speaking', 'Speaking'), ('singing', 'Singing')], default='speaking', max_length=20),
        ),
        migrations.AddField(
            model_name='voiceprofile',
            name='chatterbox_embedding_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='voiceprofile',
            name='rvc_model_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='voiceprofile',
            name='singing_status',
            field=models.CharField(choices=[('pending', 'Pending Samples'), ('enrolling', 'Enrolling'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='voiceprofile',
            name='speaking_status',
            field=models.CharField(choices=[('pending', 'Pending Samples'), ('enrolling', 'Enrolling'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='voicesample',
            name='sample_type',
            field=models.CharField(choices=[('speaking', 'Speaking'), ('singing', 'Singing')], default='speaking', max_length=20),
        ),
        migrations.AddIndex(
            model_name='voiceenrollmentjob',
            index=models.Index(fields=['voice_profile', 'job_type', 'status'], name='voices_voic_voice_p_d3b2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceprofile',
            index=models.Index(fields=['user', 'speaking_status'], name='voices_voic_user_id_0f47bb_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceprofile',
            index=models.Index(fields=['user', 'singing_status'], name='voices_voic_user_id_da1c99_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesample',
            index=models.Index(fields=['voice_profile', 'sample_type'], name='voices_voic_voice_p_4dd657_idx'),
        ),
    ]
