# Generated by Django 5.2.9 on 2025-12-17 01:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('voices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_song_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('pitch_shift', models.SmallIntegerField(default=0)),
                ('vocal_volume', models.FloatField(default=1.0)),
                ('instrumental_volume', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_jobs', to=settings.AUTH_USER_MODEL)),
                ('voice_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_jobs', to='voices.voiceprofile')),
            ],
            options={
                'verbose_name': 'Cover Job',
                'verbose_name_plural': 'Cover Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('format', models.CharField(choices=[('wav', 'WAV'), ('mp3', 'MP3'), ('flac', 'FLAC'), ('ogg', 'OGG')], default='wav', max_length=10)),
                ('duration_seconds', models.FloatField()),
                ('sample_rate', models.PositiveIntegerField(default=44100)),
                ('channels', models.PositiveSmallIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeparatedTracks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vocals_path', models.CharField(max_length=500)),
                ('instrumentals_path', models.CharField(max_length=500)),
                ('converted_vocals_path', models.CharField(blank=True, max_length=500)),
                ('sample_rate', models.PositiveIntegerField(default=44100)),
                ('duration_seconds', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='separated_tracks', to='tts.coverjob')),
            ],
            options={
                'verbose_name': 'Separated Tracks',
                'verbose_name_plural': 'Separated Tracks',
            },
        ),
        migrations.CreateModel(
            name='TTSJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_jobs', to=settings.AUTH_USER_MODEL)),
                ('voice_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tts_jobs', to='voices.voiceprofile')),
            ],
            options={
                'verbose_name': 'TTS Job',
                'verbose_name_plural': 'TTS Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coverjob',
            index=models.Index(fields=['user', 'status'], name='tts_coverjo_user_id_899b43_idx'),
        ),
        migrations.AddIndex(
            model_name='coverjob',
            index=models.Index(fields=['created_at'], name='tts_coverjo_created_8b6186_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedaudio',
            index=models.Index(fields=['content_type', 'object_id'], name='tts_generat_content_c31a05_idx'),
        ),
        migrations.AddIndex(
            model_name='ttsjob',
            index=models.Index(fields=['user', 'status'], name='tts_ttsjob_user_id_ce75c6_idx'),
        ),
        migrations.AddIndex(
            model_name='ttsjob',
            index=models.Index(fields=['created_at'], name='tts_ttsjob_created_146c0f_idx'),
        ),
    ]
